/*
 * This Java source file was generated by the Gradle 'init' task.
 */

package restaurant;

import gamegrub.data.drinks.Candy;
import gamegrub.data.drinks.Cranium;
import gamegrub.data.drinks.Sorry;
import gamegrub.data.entrees.Chess;
import gamegrub.data.entrees.Clue;
import gamegrub.data.entrees.Jenga;
import gamegrub.data.entrees.Monopoly;
import gamegrub.data.entrees.Yahtzee;
import gamegrub.data.enums.Base;
import gamegrub.data.enums.Size;
import gamegrub.data.enums.Toppings;
import gamegrub.data.sides.Catan;
import gamegrub.data.sides.Dice;
import gamegrub.data.sides.Risk;


/**
 * Class for App.
 *
 *<p>I honestly do not know what this is
 */
public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    /**
     * Main class.
     */
    public static void main(String[] args) {
        // System.out.println(new App().getGreeting());
    }
}
